apiVersion: batch/v1
kind: CronJob
metadata:
  name: uiload-cron
spec:
  schedule: "*/1 * * * *"   # every 1 minute
  concurrencyPolicy: Forbid  
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uiload
            image: mukundbabbar/uiload:latest
            env:
            - name: ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: appd-config
                  key: ENDPOINT_URL
          restartPolicy: Never
